// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIviAmmYr-pQqZaw_wbeW2ThHFh0jkus',
    appId: '1:61150833711:web:e025774d6094b43df12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    authDomain: 'notes-app-27f3e.firebaseapp.com',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
    measurementId: 'G-K6MTV2DEPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXF_pT85cguRFxk9A4g460_zip92ejeJk',
    appId: '1:61150833711:android:9a3e415bd3d22f79f12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJioMtnz-4NNyZgefDyQoZSFtsorKk-_Q',
    appId: '1:61150833711:ios:f86818de1dceb47df12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJioMtnz-4NNyZgefDyQoZSFtsorKk-_Q',
    appId: '1:61150833711:ios:f86818de1dceb47df12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXIviAmmYr-pQqZaw_wbeW2ThHFh0jkus',
    appId: '1:61150833711:web:96d0881111f3dc8cf12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    authDomain: 'notes-app-27f3e.firebaseapp.com',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
    measurementId: 'G-2RL4QBS1SC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDXIviAmmYr-pQqZaw_wbeW2ThHFh0jkus',
    appId: '1:61150833711:web:96d0881111f3dc8cf12ada',
    messagingSenderId: '61150833711',
    projectId: 'notes-app-27f3e',
    authDomain: 'notes-app-27f3e.firebaseapp.com',
    storageBucket: 'notes-app-27f3e.firebasestorage.app',
    measurementId: 'G-2RL4QBS1SC',
  );
}
